---

apiVersion: v1
kind: ConfigMap

metadata:
  name: vector-logs-aggregator-config
  namespace: kube-system

data:
  vector.yaml: |
    api:
      enabled: true
      address: 0.0.0.0:8686

    sources:
      vector:
        type: vector
        address: 0.0.0.0:8685

    transforms:
      final_transform:
        type: remap
        inputs: [ vector ]
        source: |
          . = .

    sinks:
      datadog:
        type: datadog_logs
        inputs: [ final_transform ]
        site: datadoghq.eu

