---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: vector-logs-aggregator
  namespace: kube-system

spec:
  selector:
    matchLabels:
      name: vector-logs-aggregator
  template:
    metadata:
      labels:
        name: vector-logs-aggregator
    spec:
      serviceAccountName: vector
      containers:
        - name: vector-logs-aggregator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args: [ "--config-dir", "/etc/vector/" ]
          ports:
            - containerPort: 8686
            - containerPort: 8685
          envFrom:
            - secretRef:
                name: {{ .Values.datadog.secretName | default "datadog-creds" }}
          volumeMounts:
            - mountPath: /etc/vector
              name: config
          livenessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: config
          configMap:
            name: vector-logs-aggregator-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service

metadata:
  name: vector-logs-aggregator

spec:
  selector:
    name: vector-logs-aggregator
  ports:
    - name: source
      port: 8685
      targetPort: 8685
