---

apiVersion: v1
kind: ConfigMap

metadata:
  name: vector-logs-aggregator-config
  namespace: {{ .Values.targetNamespace }}

data:
  vector.yaml: |
    api:
      enabled: true
      address: "0.0.0.0:{{ .Values.vector.api.port }}"

    sources:
      vector:
        type: vector
        address: "0.0.0.0:{{ .Values.vector.aggregator.source.port }}"

    transforms:
      final_transform:
        type: remap
        inputs: [ vector ]
        source: |
          . = .

    sinks:
      datadog:
        type: datadog_logs
        inputs: [ final_transform ]
        site: {{ .Values.datadog.site }}

