---

apiVersion: v1
kind: ConfigMap

metadata:
  name: vector-logs-sender-config
  namespace: kube-system

data:
  vector.yaml: |
    api:
      enabled: true
      address: 0.0.0.0:8686

    sources:
      logs:
        type: kubernetes_logs
        self_node_name: ${VECTOR_SELF_NODE_NAME}

    transforms:
      sample_logs:
        type: sample
        inputs: [ logs ]
        rate: 500
      parse_json:
        type: remap
        inputs: [ logs ]
        source: |
          . = merge!(., parse_json(.message) ?? parse_key_value(.message) ?? {})
          .@timestamp = del(.timestamp)
          if exists(.msg) {
            .message = del(.msg)
          }
          if exists(.logger_name) {
            .logger_name_full = .logger_name
            .logger_name = replace!(.logger_name, r'(?P<fl>\w)\w+\.', "$$fl.") # Convert `com.example.Foo` to `c.e.Foo`
          }
          .service = .kubernetes.container_name
          .hostname = .kubernetes.pod_name
          del(.file)
          del(.kubernetes)
          del(.@version)
          del(.level_value)
          del(.source_type)
          del(.stream)
      exclude_log_levels:
        type: filter
        inputs: [ parse_json ]
        condition: |
          !includes(
            [
              {{- range .Values.sender.exclude.logLevels }}
                "{{ . }}",
              {{- end }}
            ],
            .level
          )

      exclude_services:
        type: filter
        inputs: [ exclude_log_levels ]
        condition: |
          !includes(
            [
              {{- range .Values.sender.exclude.services }}
                "{{ . }}",
              {{- end }}
            ],
            .service
          )
      # Placeholder transform to always refer to the last transform in the sinks section
      final_transform:
        type: remap
        inputs: [ exclude_services ]
        source: |
          . = .

    sinks:
      vector_aggregator:
        type: vector
        inputs: [ final_transform ]
        address: vector-logs-aggregator.kube-system.svc.cluster.local:8685
      #console:
      #  type: console
      #  inputs: [ final_transform ]
      #  encoding:
      #    codec: json
