image:
  repository: timberio/vector
  tag: latest-alpine

# Name of the secret containing Datadog credentials.
# It should contain:
# * DD_API_KEY – (required) API key for your Datadog account
datadog:
  secretName: datadog-secret
  site: datadoghq.com

sender:
  exclude:
    # List of services to exclude from sending. Leave empty to send logs from all services.
    services:
      - argocd-application-controller
      - argocd-applicationset-controller
      - argocd-notifications-controller
      - argocd-image-updater
      - argocd-repo-server
      - argocd-server
      - vector-logs-sender
      - vector-logs-aggregator

    # List of log levels to exclude from sending. Leave empty to disable filtering by log level.
    logLevels:
      - TRACE
      - DEBUG